// <auto-generated />
namespace Sports_Betting_Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Inital : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inital));
        
        string IMigrationMetadata.Id
        {
            get { return "201806151503375_Inital"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
